### ISSUE TITLE
CMake errors CXX_STANDARD is set to invalid value 17

### ISSUE THREAD

**Issue by AS383** [geontime/redkite#14]
Release 0.6.3 configured by Cmake 3.7.2 with errors and does not build:
CMake Error at CMakeLists.txt:179 (add_library):
  CXX_STANDARD is set to invalid value '17'

**Comment by iurienistor** [comment]
Hi, thank you. You need to use CMake >= 3.8. I'll update the minimum required CMake version that supports value 17.
